SOURCES = exercises.ml

RESULT = exercises

INCDIRS = ../../more/ ../../examples/Chapter4/ ../../examples/Chapter5/

LIBS = unix more input bits 

OCAMLNCFLAGS = -g
OCAMLBCFLAGS = -g
OCAMLLDFLAGS = -g

all : native-code top

OCAMLMAKEFILE = ../../more/OCamlMakefile

include $(OCAMLMAKEFILE)
