SOURCES = examples.ml

RESULT = examples

INCDIRS = ../../more/ ../Chapter5/ ../Chapter4/

LIBS = bits

OCAMLNCFLAGS = -g
OCAMLBCFLAGS = -g
OCAMLLDFLAGS = -g

all : byte-code top

OCAMLMAKEFILE = ../../more/OCamlMakefile

include $(OCAMLMAKEFILE)
