SOURCES = input.ml text.ml

RESULT = text

INCDIRS = ../../../more/ ../../../examples/PDF/ ../../../examples

LIBS = more pdfmain 

OCAMLNCFLAGS = -g
OCAMLBCFLAGS = -g
OCAMLLDFLAGS = -g

all : native-code top

OCAMLMAKEFILE = ../../../more/OCamlMakefile

include $(OCAMLMAKEFILE)

